name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: xhengiz/GithubActionDockerTest@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag GithubActionDockerTest:$(date +%s)
