name: Docker Image CI

on: [pushX]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: xhengiz/GithubActionDockerTest@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}           
    - name: Build the Docker image
      run: docker build -t githubactiondockertest . 
