name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: xhengiz/GithubActionDockerTest@master
    - name: Setup .NET Core
      uses: xhengiz/GithubActionDockerTest@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}      
    - name: Build with dotnet
      run: dotnet build
